# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Indice
email: elvessousa@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  A Simple TOC for simple needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://indice.elvessousa.com.br" # the base hostname & protocol for your site
twitter_username: elvessousa
github_username:  elvessousa

# Facebook App ID
fbid: 265099963530379

# Build settings
markdown: kramdown
